name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
